In [1]:
import pandas as pd

In [2]:
import os

print(os.getcwd())

g:\vendor performance analysis\Notebook

In [3]:
import os

print(os.listdir("../data/raw"))

['begin_inventory.csv', 'end_inventory.csv', 'inventory.db', 'purchases.csv', 'purchase_prices.csv', 'sales.csv', 'vendor_invoice.csv', 'vendor_sales_summary.csv']

In [4]:
sales = pd.read_csv(r"G:\vendor performance analysis\Data\Raw\sales.csv")
sales.head()

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

In [5]:
sales.shape

(12825363, 14)

In [6]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='str')

In [7]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 12825363 entries, 0 to 12825362
Data columns (total 14 columns):
 #   Column          Dtype
---  ------          -----
 0   InventoryId     str
 1   Store           int64
 2   Brand           int64
 3   Description     str
 4   Size            str
 5   SalesQuantity   int64
 6   SalesDollars    float64
 7   SalesPrice      float64
 8   SalesDate       str
 9   Volume          float64
 10  Classification  int64
 11  ExciseTax       float64
 12  VendorNo        int64
 13  VendorName      str
dtypes: float64(4), int64(5), str(5)
memory usage: 2.3 GB

In [8]:
sales.isnull().sum()

InventoryId       0
Store             0
Brand             0
Description       0
Size              0
SalesQuantity     0
SalesDollars      0
SalesPrice        0
SalesDate         0
Volume            0
Classification    0
ExciseTax         0
VendorNo          0
VendorName        0
dtype: int64

In [9]:
sales.duplicated().sum()

np.int64(0)

In [10]:
sales.describe()

,Store,Brand,SalesQuantity,SalesDollars,SalesPrice,Volume,Classification,ExciseTax,VendorNo
count,1.282536e+07,1.282536e+07,1.282536e+07,1.282536e+07,1.282536e+07,1.282536e+07,1.282536e+07,1.282536e+07,1.282536e+07
mean,4.389572e+01,1.215460e+04,2.566623e+00,3.524758e+01,1.569027e+01,9.394389e+02,1.413892e+00,1.479431e+00,7.125907e+03
std,2.353947e+01,1.236843e+04,4.551810e+00,8.835689e+01,1.512728e+01,6.993202e+02,4.925295e-01,4.736633e+00,8.742565e+03
min,1.000000e+00,5.800000e+01,1.000000e+00,0.000000e+00,0.000000e+00,5.000000e+01,1.000000e+00,1.000000e-02,2.000000e+00
25%,2.300000e+01,3.663000e+03,1.000000e+00,1.099000e+01,8.990000e+00,7.500000e+02,1.000000e+00,2.100000e-01,3.252000e+03
50%,4.700000e+01,6.349000e+03,1.000000e+00,1.899000e+01,1.299000e+01,7.500000e+02,1.000000e+00,7.500000e-01,4.692000e+03
75%,6.600000e+01,1.795400e+04,2.000000e+00,3.499000e+01,1.899000e+01,1.000000e+03,2.000000e+00,1.570000e+00,9.552000e+03
max,8.100000e+01,9.063100e+04,1.231000e+03,2.606114e+04,5.799990e+03,2.000000e+04,2.000000e+00,1.260520e+03,2.013590e+05

In [11]:
sales.columns.tolist()

['InventoryId',
 'Store',
 'Brand',
 'Description',
 'Size',
 'SalesQuantity',
 'SalesDollars',
 'SalesPrice',
 'SalesDate',
 'Volume',
 'Classification',
 'ExciseTax',
 'VendorNo',
 'VendorName']

In [12]:
sales.sample(5)

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
7830459,66_EANVERNESS_23271,66,23271,Darkhorse Merlot,750mL,1,7.99,7.99,2024-08-02,750.0,2,0.11,3252,E & J GALLO WINERY
7496332,41_LARNWICK_5353,41,5353,Grand Marnier,375mL,2,37.98,18.99,2024-08-08,375.0,1,0.79,8112,MOET HENNESSY USA INC
6375680,48_NORFOLK_5447,48,5447,Jagermeister Liqueur,375mL,3,29.97,9.99,2024-07-17,375.0,1,1.18,3089,SIDNEY FRANK IMPORTING CO
5425174,60_IRRAGIN_5872,60,5872,Godiva Chocolate Liqueur,50mL,2,5.98,2.99,2024-06-17,50.0,1,0.10,3960,DIAGEO NORTH AMERICA INC
7628781,52_GRAYCOTT_2663,52,2663,Dewars White Label,1.75L,5,149.95,29.99,2024-08-29,1750.0,1,9.19,480,BACARDI USA INC

In [13]:
sales.dtypes

InventoryId           str
Store               int64
Brand               int64
Description           str
Size                  str
SalesQuantity       int64
SalesDollars      float64
SalesPrice        float64
SalesDate             str
Volume            float64
Classification      int64
ExciseTax         float64
VendorNo            int64
VendorName            str
dtype: object

In [14]:
sales["SalesDate"].min(), sales["SalesDate"].max()

('2024-01-01', '2024-12-31')

In [15]:
sales["VendorNo"].nunique()

127

In [16]:
sales["VendorName"].nunique()

130

In [17]:
sales.groupby("VendorName")["SalesDollars"].sum().sort_values(ascending=False).head(10)

VendorName
DIAGEO NORTH AMERICA INC       68742416.99
MARTIGNETTI COMPANIES          40992395.93
PERNOD RICARD USA              32281247.95
JIM BEAM BRANDS COMPANY        31906320.54
BACARDI USA INC                25014556.89
CONSTELLATION BRANDS INC       24469172.93
E & J GALLO WINERY             18556085.61
BROWN-FORMAN CORP              18478557.47
ULTRA BEVERAGE COMPANY LLP     17822938.45
M S WALKER INC                 15465247.75
Name: SalesDollars, dtype: float64

In [18]:
sales.shape

(12825363, 14)

In [19]:
sales["SalesDollars"].sum()

np.float64(452062952.02000004)

In [20]:
sales["SalesQuantity"].sum()

np.int64(32917876)

In [21]:
vendor_name_counts = sales.groupby("VendorNo")["VendorName"].nunique()

vendor_name_counts[vendor_name_counts > 1]

VendorNo
1587    2
2000    2
4425    2
Name: VendorName, dtype: int64

In [22]:
vendor_number_counts = sales.groupby("VendorName")["VendorNo"].nunique()

vendor_number_counts[vendor_number_counts > 1]

Series([], Name: VendorNo, dtype: int64)

In [23]:
sales[sales["VendorNo"].isin(vendor_name_counts[vendor_name_counts > 1].index)][
    ["VendorNo", "VendorName"]
].drop_duplicates().sort_values("VendorNo")

          VendorNo                   VendorName
1009          1587  VINEYARD BRANDS INC
10748135      1587  VINEYARD BRANDS LLC
8225794       2000  SOUTHERN GLAZERS W&S OF NE
8             2000  SOUTHERN WINE & SPIRITS NE
2555          4425       MARTIGNETTI COMPANIES
40            4425        MARTIGNETTI COMPANIES

In [24]:
vendor_number_counts = sales.groupby("VendorName")["VendorNo"].nunique()

vendor_number_counts[vendor_number_counts > 1]

Series([], Name: VendorNo, dtype: int64)

In [25]:
sales[sales["VendorNo"].isin([1587, 2000, 4425])][
    ["VendorNo", "VendorName"]
].drop_duplicates().sort_values("VendorNo")

          VendorNo                   VendorName
1009          1587  VINEYARD BRANDS INC
10748135      1587  VINEYARD BRANDS LLC
8225794       2000  SOUTHERN GLAZERS W&S OF NE
8             2000  SOUTHERN WINE & SPIRITS NE
2555          4425       MARTIGNETTI COMPANIES
40            4425        MARTIGNETTI COMPANIES

In [26]:
sales[sales["VendorNo"].isin([1587, 2000, 4425])].groupby(
    ["VendorNo", "VendorName"]
).agg(
    Transactions=("InventoryId", "count"),
    Sales=("SalesDollars", "sum")
).reset_index()

   VendorNo                   VendorName  Transactions        Sales
0      1587  VINEYARD BRANDS INC                 69232   1845237.53
1      1587  VINEYARD BRANDS LLC                    68      4323.96
2      2000  SOUTHERN GLAZERS W&S OF NE           1450     40440.12
3      2000  SOUTHERN WINE & SPIRITS NE         174107   5729494.21
4      4425        MARTIGNETTI COMPANIES        939764  40992395.93
5      4425       MARTIGNETTI COMPANIES           1869     54910.37

In [27]:
purchases = pd.read_csv(r"G:\vendor performance analysis\Data\Raw\purchases.csv")

In [28]:
purchases.head()

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

In [29]:
purchases.shape

(2372474, 16)

In [30]:
purchases.columns.tolist()

['InventoryId',
 'Store',
 'Brand',
 'Description',
 'Size',
 'VendorNumber',
 'VendorName',
 'PONumber',
 'PODate',
 'ReceivingDate',
 'InvoiceDate',
 'PayDate',
 'PurchasePrice',
 'Quantity',
 'Dollars',
 'Classification']

In [31]:
purchases.dtypes

InventoryId           str
Store               int64
Brand               int64
Description           str
Size                  str
VendorNumber        int64
VendorName            str
PONumber            int64
PODate                str
ReceivingDate         str
InvoiceDate           str
PayDate               str
PurchasePrice     float64
Quantity            int64
Dollars           float64
Classification      int64
dtype: object

In [32]:
purchases.isnull().sum()

InventoryId       0
Store             0
Brand             0
Description       0
Size              3
VendorNumber      0
VendorName        0
PONumber          0
PODate            0
ReceivingDate     0
InvoiceDate       0
PayDate           0
PurchasePrice     0
Quantity          0
Dollars           0
Classification    0
dtype: int64

In [33]:
purchases["VendorNumber"].nunique()

126

In [34]:
purchases["Dollars"].sum()

np.float64(321900765.53)

In [35]:
purchase_prices = pd.read_csv(r"G:\vendor performance analysis\Data\Raw\purchase_prices.csv")

In [36]:
purchase_prices.head()

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

In [37]:
purchase_prices.shape

(12261, 9)

In [38]:
purchase_prices.dtypes

Brand               int64
Description           str
Price             float64
Size                  str
Volume                str
Classification      int64
PurchasePrice     float64
VendorNumber        int64
VendorName            str
dtype: object

In [39]:
purchase_prices.isnull().sum()

Brand             0
Description       1
Price             0
Size              1
Volume            1
Classification    0
PurchasePrice     0
VendorNumber      0
VendorName        0
dtype: int64

In [40]:
purchase_prices.duplicated().sum()

np.int64(0)

In [41]:
begin_inventory = pd.read_csv(r"G:\vendor performance analysis\Data\Raw\begin_inventory.csv")

In [42]:
begin_inventory.head()

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

In [43]:
begin_inventory.shape

(206529, 9)

In [44]:
begin_inventory.dtypes

InventoryId        str
Store            int64
City               str
Brand            int64
Description        str
Size               str
onHand           int64
Price          float64
startDate          str
dtype: object

In [45]:
begin_inventory.isnull().sum()

InventoryId    0
Store          0
City           0
Brand          0
Description    0
Size           0
onHand         0
Price          0
startDate      0
dtype: int64

In [46]:
begin_inventory.duplicated().sum()

np.int64(0)

In [47]:
end_inventory = pd.read_csv(
    r"G:\vendor performance analysis\Data\Raw\end_inventory.csv"
)

In [48]:
end_inventory.head()

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

In [49]:
end_inventory.shape

(224489, 9)

In [50]:
end_inventory.columns.tolist()

['InventoryId',
 'Store',
 'City',
 'Brand',
 'Description',
 'Size',
 'onHand',
 'Price',
 'endDate']

In [51]:
end_inventory.dtypes

InventoryId        str
Store            int64
City               str
Brand            int64
Description        str
Size               str
onHand           int64
Price          float64
endDate            str
dtype: object

In [52]:
end_inventory.isnull().sum()

InventoryId       0
Store             0
City           1284
Brand             0
Description       0
Size              0
onHand            0
Price             0
endDate           0
dtype: int64

In [53]:
end_inventory.duplicated().sum()

np.int64(0)

In [54]:
vendor_invoice = pd.read_csv(r"G:\vendor performance analysis\Data\Raw\vendor_invoice.csv")

In [55]:
vendor_invoice.head()

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,NaN
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,NaN
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,NaN
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,NaN
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,NaN

In [56]:
vendor_invoice.shape

(5543, 10)

In [57]:
vendor_invoice.dtypes

VendorNumber      int64
VendorName          str
InvoiceDate         str
PONumber          int64
PODate              str
PayDate             str
Quantity          int64
Dollars         float64
Freight         float64
Approval            str
dtype: object

In [58]:
vendor_invoice.isnull().sum()

VendorNumber       0
VendorName         0
InvoiceDate        0
PONumber           0
PODate             0
PayDate            0
Quantity           0
Dollars            0
Freight            0
Approval        5169
dtype: int64

In [59]:
vendor_invoice.duplicated().sum()

np.int64(0)

In [60]:
vendor_sales_summary = pd.read_csv(r"G:\vendor performance analysis\Data\Raw\vendor_sales_summary.csv")

In [61]:
vendor_sales_summary.head()

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesPrice,TotalSalesDollars,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,142049.0,672819.31,5101919.51,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,160247.0,561512.37,4819073.49,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,187140.0,461140.15,4538120.60,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,200412.0,420050.01,4475972.88,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,135838.0,545778.28,4223107.62,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897

In [62]:
vendor_sales_summary.shape

(10692, 18)

In [63]:
vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                   str
Brand                      int64
Description                  str
PurchasePrice            float64
ActualPrice              float64
Volume                   float64
TotalPurchaseQuantity      int64
TotalPurchaseDollars     float64
TotalSalesQuantity       float64
TotalSalesPrice          float64
TotalSalesDollars        float64
TotalExciseTax           float64
FreightCost              float64
GrossProfit              float64
ProfitMargin             float64
StockTurnover            float64
SalestoPurchaseRatio     float64
dtype: object

In [64]:
vendor_sales_summary.isnull().sum()

VendorNumber             0
VendorName               0
Brand                    0
Description              0
PurchasePrice            0
ActualPrice              0
Volume                   0
TotalPurchaseQuantity    0
TotalPurchaseDollars     0
TotalSalesQuantity       0
TotalSalesPrice          0
TotalSalesDollars        0
TotalExciseTax           0
FreightCost              0
GrossProfit              0
ProfitMargin             0
StockTurnover            0
SalestoPurchaseRatio     0
dtype: int64

In [65]:
vendor_sales_summary.duplicated().sum()

np.int64(0)

In [66]:
sales["SalesDate"] = pd.to_datetime(sales["SalesDate"])

In [67]:
sales.dtypes["SalesDate"]

dtype('<M8[us]')

In [68]:
sales["SalesDate"].isnull().sum()

np.int64(0)

In [69]:
vendor_mapping = sales[["VendorNo", "VendorName"]].drop_duplicates()

In [70]:
vendor_mapping[
    vendor_mapping["VendorNo"].isin([1587, 2000, 4425])
].sort_values("VendorNo")

          VendorNo                   VendorName
1009          1587  VINEYARD BRANDS INC
10748135      1587  VINEYARD BRANDS LLC
8225794       2000  SOUTHERN GLAZERS W&S OF NE
8             2000  SOUTHERN WINE & SPIRITS NE
2555          4425       MARTIGNETTI COMPANIES
40            4425        MARTIGNETTI COMPANIES

In [71]:
vendor_mapping.groupby("VendorNo")["VendorName"].nunique().sort_values(ascending=False).head()

VendorNo
1587    2
2000    2
4425    2
200     1
287     1
Name: VendorName, dtype: int64

In [72]:
purchases[purchases["VendorNumber"].isin([1587, 2000, 4425])][
    ["VendorNumber", "VendorName"]
].drop_duplicates().sort_values("VendorNumber")

         VendorNumber                   VendorName
7582             1587  VINEYARD BRANDS INC
2100628          1587  VINEYARD BRANDS LLC
1593834          2000  SOUTHERN GLAZERS W&S OF NE
6628             2000  SOUTHERN WINE & SPIRITS NE
4295             4425       MARTIGNETTI COMPANIES
4297             4425        MARTIGNETTI COMPANIES

In [73]:
vendor_invoice[vendor_invoice["VendorNumber"].isin([1587, 2000, 4425])][
    ["VendorNumber", "VendorName"]
].drop_duplicates().sort_values("VendorNumber")

      VendorNumber                   VendorName
81            1587  VINEYARD BRANDS INC
5006          1587  VINEYARD BRANDS LLC
3793          2000  SOUTHERN GLAZERS W&S OF NE
67            2000  SOUTHERN WINE & SPIRITS NE
42            4425       MARTIGNETTI COMPANIES
43            4425        MARTIGNETTI COMPANIES

In [74]:
vendor_sales_summary[
    vendor_sales_summary["VendorNumber"].isin([1587, 2000, 4425])
][["VendorNumber", "VendorName"]].drop_duplicates().sort_values("VendorNumber")

      VendorNumber                  VendorName
601           1587         VINEYARD BRANDS INC
5157          1587         VINEYARD BRANDS LLC
2642          2000  SOUTHERN GLAZERS W&S OF NE
156           2000  SOUTHERN WINE & SPIRITS NE
1             4425       MARTIGNETTI COMPANIES

In [75]:
sales["VendorID"] = sales["VendorNo"]

In [76]:
sales[["VendorID", "VendorName"]].head()

   VendorID                   VendorName
0     12546  JIM BEAM BRANDS COMPANY
1     12546  JIM BEAM BRANDS COMPANY
2     12546  JIM BEAM BRANDS COMPANY
3     12546  JIM BEAM BRANDS COMPANY
4     12546  JIM BEAM BRANDS COMPANY

In [77]:
sales_vendors = set(sales["VendorNo"].unique())
purchase_vendors = set(purchases["VendorNumber"].unique())

sales_vendors - purchase_vendors

{np.int64(1002), np.int64(9710), np.int64(90034)}

In [78]:
sales[sales["VendorNo"].isin([1002, 9710, 90034])][
    ["VendorNo", "VendorName"]
].drop_duplicates()

         VendorNo                   VendorName
374815       9710  WHYTE & MACKAY
873327       1002  BERNIKO LLC
1201093     90034  EXCLUSIVE WINES & SPIRITS

In [79]:
sales[sales["VendorNo"].isin([1002, 9710, 90034])].groupby(
    ["VendorNo", "VendorName"]
)["SalesDollars"].sum()

VendorNo  VendorName
1002      BERNIKO LLC                    16.99
9710      WHYTE & MACKAY                 31.98
90034     EXCLUSIVE WINES & SPIRITS      55.98
Name: SalesDollars, dtype: float64

In [80]:
sales[sales["VendorNo"].isin([1002, 9710, 90034])].groupby(
    ["VendorNo", "VendorName"]
).size()

VendorNo  VendorName
1002      BERNIKO LLC                    1
9710      WHYTE & MACKAY                 1
90034     EXCLUSIVE WINES & SPIRITS      1
dtype: int64

In [81]:
purchases[purchases["Size"].isnull()]

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
1109668,34_PITMERDEN_3121,34,3121,Pinnacle Rainbow Sherbet,NaN,12546,JIM BEAM BRANDS COMPANY,10938,2024-06-27,2024-07-04,2024-07-13,2024-08-16,6.93,7,48.51,1
1112426,34_PITMERDEN_5678,34,5678,Skinnygirl Pina Colada,NaN,12546,JIM BEAM BRANDS COMPANY,10938,2024-06-27,2024-07-09,2024-07-13,2024-08-16,6.93,6,41.58,1
1116302,39_EASTHALLOW_15365,39,15365,Alabaster 07 Tinta de Toro,NaN,9552,M S WALKER INC,10972,2024-06-29,2024-07-07,2024-07-13,2024-08-21,91.83,1,91.83,2

In [82]:
purchase_prices[
    purchase_prices["Brand"].isin([3121, 5678, 15365])
][["Brand", "Description", "Size", "Volume", "VendorNumber", "VendorName"]]

,Brand,Description,Size,Volume,VendorNumber,VendorName
572,3121,Pinnacle Rainbow Sherbet,750mL,750,12546,JIM BEAM BRANDS COMPANY
1305,5678,Skinnygirl Pina Colada,750mL,750,12546,JIM BEAM BRANDS COMPANY
6933,15365,Alabaster 07 Tinta de Toro,750mL,750,9552,M S WALKER INC

In [83]:
sales[
    sales["Brand"].isin([3121, 5678, 15365])
][["Brand", "Description", "Size", "VendorNo", "VendorName"]].drop_duplicates()

,Brand,Description,Size,VendorNo,VendorName
46235,5678,Skinnygirl Pina Colada,750mL,12546,JIM BEAM BRANDS COMPANY
101071,3121,Pinnacle Rainbow Sherbet,750mL,12546,JIM BEAM BRANDS COMPANY
2676596,15365,Alabaster 07 Tinta de Toro,750mL,9552,M S WALKER INC

In [84]:
purchases.loc[
    purchases["Brand"].isin([3121, 5678, 15365]) & purchases["Size"].isnull(),
    "Size"
] = "750mL"

In [85]:
purchases["Size"].isnull().sum()

np.int64(0)

In [86]:
purchase_prices[
    purchase_prices[["Description", "Size", "Volume"]].isnull().any(axis=1)
]

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
7915,4202,NaN,0.0,NaN,NaN,1,11.19,480,BACARDI USA INC

In [87]:
purchases[
    purchases["Brand"] == 4202
][["Brand", "Description", "Size", "VendorNumber", "VendorName", "PurchasePrice"]].drop_duplicates()

Empty DataFrame
Columns: [Brand, Description, Size, VendorNumber, VendorName, PurchasePrice]
Index: []

In [88]:
sales[
    sales["Brand"] == 4202
][["Brand", "Description", "Size", "SalesPrice", "VendorNo", "VendorName"]].drop_duplicates()

Empty DataFrame
Columns: [Brand, Description, Size, SalesPrice, VendorNo, VendorName]
Index: []

In [89]:
begin_inventory[
    begin_inventory["Brand"] == 4202
][["Brand", "Description", "Size", "Price"]].drop_duplicates()

Empty DataFrame
Columns: [Brand, Description, Size, Price]
Index: []

In [90]:
vendor_invoice[
    vendor_invoice["VendorNumber"] == 480
][["VendorNumber", "VendorName"]].drop_duplicates()

   VendorNumber                   VendorName
3           480  BACARDI USA INC

In [91]:
vendor_sales_summary[
    (vendor_sales_summary["VendorNumber"] == 480) &
    (vendor_sales_summary["Brand"] == 4202)
]

Empty DataFrame
Columns: [VendorNumber, VendorName, Brand, Description, PurchasePrice, ActualPrice, Volume, TotalPurchaseQuantity, TotalPurchaseDollars, TotalSalesQuantity, TotalSalesPrice, TotalSalesDollars, TotalExciseTax, FreightCost, GrossProfit, ProfitMargin, StockTurnover, SalestoPurchaseRatio]
Index: []

In [92]:
purchase_prices[purchase_prices["Price"] == 0]

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
7915,4202,NaN,0.0,NaN,NaN,1,11.19,480,BACARDI USA INC
10803,2166,The Macallan Double Cask 12,0.0,750mL,750,1,0.00,2561,EDRINGTON AMERICAS

In [93]:
purchase_prices[
    (purchase_prices["VendorNumber"] == 480)
][["Brand", "Description", "Price", "Size", "Volume", "PurchasePrice"]].head(20)

     Brand                   Description   Price    Size Volume  PurchasePrice
8      126              Grey Goose Vodka   32.99  1000mL   1000          20.14
39     443            St Germain Liqueur   33.99   750mL    750          24.45
45     508          Bacardi Superior Rum   12.99  1000mL   1000           9.77
68     743           Angels Envy Whiskey   45.99   750mL    750          36.50
76     802    Bacardi Torched Cherry Rum   11.99   750mL    750           7.99
79     810            Bacardi Black Razz   11.99   750mL    750           7.19
85     824     Dewars White Label Scotch   26.99  1000mL   1000          20.76
99     903           Bombay Sapphire Gin   24.99  1000mL   1000          18.79
106    973       Bacardi 1873 Solera Rum   19.99   750mL    750          11.90
111   1099  Angel's Envy NH Blend Bourbn   45.99   750mL    750          33.33
112   1106         Aberfeldy Single Cask  249.99   750mL    750         155.55
284   2123              Angel's Envy Rye   79.99   750mL    750          57.96
311   2184       Bonnie Rose Orange Peel   19.99   750mL    750          11.36
316   2200      Bonnie Rose Spiced Apple   19.99   750mL    750          10.78
332   2258  Dewars Special Reserve 12 Yr   16.99   375mL    375           9.77
341   2329    Craigellachie 13 Yr Scotch   54.99   750mL    750          38.45
402   2611         Dewar's 15 Yr Old Rsv   54.99   750mL    750          39.99
403   2614    Dewars Special RSV 12-Year   59.99  1750mL   1750          41.21
406   2622    Dewars Scratch Cask Scotch   26.99   750mL    750          18.65
408   2624  Dewars 18 Yr Old Founders Rv   64.99   750mL    750          46.76

In [94]:
purchase_prices[
    (purchase_prices["VendorNumber"] == 480) &
    (purchase_prices["Brand"] == 4202)
]

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
7915,4202,NaN,0.0,NaN,NaN,1,11.19,480,BACARDI USA INC

In [95]:
purchase_prices[
    purchase_prices["Brand"] == 4202
][["Brand", "Description", "Price", "Size", "Volume",
   "PurchasePrice", "VendorNumber", "VendorName"]]

,Brand,Description,Price,Size,Volume,PurchasePrice,VendorNumber,VendorName
7915,4202,NaN,0.0,NaN,NaN,11.19,480,BACARDI USA INC

In [96]:
missing_city = end_inventory[end_inventory["City"].isnull()]

missing_city.shape

(1284, 9)

In [97]:
missing_city["Store"].value_counts()

Store
46    1284
Name: count, dtype: int64

In [98]:
begin_inventory[
    begin_inventory["Store"].isin(missing_city["Store"].unique())
][["Store", "City"]].drop_duplicates().sort_values("Store")

        Store         City
108343     46  TYWARDREATH

In [99]:
end_inventory.loc[end_inventory["City"].isnull(), "City"] = "TYWARDREATH"

In [100]:
end_inventory["City"].isnull().sum()

np.int64(0)

In [101]:
vendor_invoice["Approval"].value_counts(dropna=False)

Approval
NaN               5169
Frank Delahunt     374
Name: count, dtype: int64

In [102]:
vendor_invoice["Approval"].unique()

<ArrowStringArray>
[nan, 'Frank Delahunt']
Length: 2, dtype: str

In [103]:
purchases[["PODate", "ReceivingDate", "InvoiceDate", "PayDate"]].dtypes

PODate           str
ReceivingDate    str
InvoiceDate      str
PayDate          str
dtype: object

In [104]:
date_columns = ["PODate", "ReceivingDate", "InvoiceDate", "PayDate"]

for col in date_columns:
    purchases[col] = pd.to_datetime(purchases[col])

In [105]:
purchases[date_columns].dtypes

PODate           datetime64[us]
ReceivingDate    datetime64[us]
InvoiceDate      datetime64[us]
PayDate          datetime64[us]
dtype: object

In [106]:
purchases[date_columns].isnull().sum()

PODate           0
ReceivingDate    0
InvoiceDate      0
PayDate          0
dtype: int64

In [107]:
begin_inventory["startDate"] = pd.to_datetime(begin_inventory["startDate"])

In [108]:
begin_inventory["startDate"].dtype

dtype('<M8[us]')

In [109]:
begin_inventory["startDate"].isnull().sum()

np.int64(0)

In [110]:
end_inventory["endDate"] = pd.to_datetime(end_inventory["endDate"])

In [111]:
end_inventory["endDate"].dtype

dtype('<M8[us]')

In [112]:
end_inventory["endDate"].isnull().sum()

np.int64(0)

In [113]:
vendor_invoice[["InvoiceDate", "PODate", "PayDate"]].dtypes

InvoiceDate    str
PODate         str
PayDate        str
dtype: object

In [114]:
date_columns = ["InvoiceDate", "PODate", "PayDate"]

for col in date_columns:
    vendor_invoice[col] = pd.to_datetime(vendor_invoice[col])

In [115]:
vendor_invoice[date_columns].dtypes

InvoiceDate    datetime64[us]
PODate         datetime64[us]
PayDate        datetime64[us]
dtype: object

In [116]:
vendor_invoice[date_columns].isnull().sum()

InvoiceDate    0
PODate         0
PayDate        0
dtype: int64

In [117]:
sales["SalesDate"].dtype

dtype('<M8[us]')

In [118]:
sales["SalesDate"] = pd.to_datetime(sales["SalesDate"])

In [119]:
sales["SalesDate"].isnull().sum()

np.int64(0)

In [120]:
sales[["SalesQuantity", "SalesDollars", "SalesPrice", "Volume", "ExciseTax"]].describe()

       SalesQuantity  SalesDollars    SalesPrice        Volume     ExciseTax
count   1.282536e+07  1.282536e+07  1.282536e+07  1.282536e+07  1.282536e+07
mean    2.566623e+00  3.524758e+01  1.569027e+01  9.394389e+02  1.479431e+00
std     4.551810e+00  8.835689e+01  1.512728e+01  6.993202e+02  4.736633e+00
min     1.000000e+00  0.000000e+00  0.000000e+00  5.000000e+01  1.000000e-02
25%     1.000000e+00  1.099000e+01  8.990000e+00  7.500000e+02  2.100000e-01
50%     1.000000e+00  1.899000e+01  1.299000e+01  7.500000e+02  7.500000e-01
75%     2.000000e+00  3.499000e+01  1.899000e+01  1.000000e+03  1.570000e+00
max     1.231000e+03  2.606114e+04  5.799990e+03  2.000000e+04  1.260520e+03

In [121]:
print("Zero SalesDollars:", (sales["SalesDollars"] == 0).sum())
print("Zero SalesPrice:", (sales["SalesPrice"] == 0).sum())

Zero SalesDollars: 55
Zero SalesPrice: 55

In [122]:
sales[
    (sales["SalesPrice"] == 0) |
    (sales["SalesDollars"] == 0)
][
    ["Brand", "Description", "SalesQuantity",
     "SalesDollars", "SalesPrice", "VendorNo", "VendorName"]
].head(20)

,Brand,Description,SalesQuantity,SalesDollars,SalesPrice,VendorNo,VendorName
1251465,25340,Dom La Soumade Rast Prestige,3,0.0,0.0,4425,MARTIGNETTI COMPANIES
1572292,25340,Dom La Soumade Rast Prestige,3,0.0,0.0,4425,MARTIGNETTI COMPANIES
1572293,25340,Dom La Soumade Rast Prestige,1,0.0,0.0,4425,MARTIGNETTI COMPANIES
1602468,25340,Dom La Soumade Rast Prestige,12,0.0,0.0,4425,MARTIGNETTI COMPANIES
1713234,25340,Dom La Soumade Rast Prestige,1,0.0,0.0,4425,MARTIGNETTI COMPANIES
3781435,19465,Flagstone Longitude Red,13,0.0,0.0,2000,SOUTHERN WINE & SPIRITS NE
3876771,19465,Flagstone Longitude Red,6,0.0,0.0,2000,SOUTHERN WINE & SPIRITS NE
3995644,19465,Flagstone Longitude Red,1,0.0,0.0,2000,SOUTHERN WINE & SPIRITS NE
4251446,19465,Flagstone Longitude Red,1,0.0,0.0,2000,SOUTHERN WINE & SPIRITS NE
4251447,19465,Flagstone Longitude Red,2,0.0,0.0,2000,SOUTHERN WINE & SPIRITS NE
4251448,19465,Flagstone Longitude Red,1,0.0,0.0,2000,SOUTHERN WINE & SPIRITS NE
4281813,19465,Flagstone Longitude Red,1,0.0,0.0,2000,SOUTHERN WINE & SPIRITS NE
4449338,19465,Flagstone Longitude Red,2,0.0,0.0,2000,SOUTHERN WINE & SPIRITS NE
4497926,19465,Flagstone Longitude Red,2,0.0,0.0,2000,SOUTHERN WINE & SPIRITS NE
5916376,3046,Ciroc Peach Vodka,1,0.0,0.0,3960,DIAGEO NORTH AMERICA INC
6032986,3046,Ciroc Peach Vodka,1,0.0,0.0,3960,DIAGEO NORTH AMERICA INC
6143436,3046,Ciroc Peach Vodka,1,0.0,0.0,3960,DIAGEO NORTH AMERICA INC
6168720,3046,Ciroc Peach Vodka,4,0.0,0.0,3960,DIAGEO NORTH AMERICA INC
6168721,3046,Ciroc Peach Vodka,1,0.0,0.0,3960,DIAGEO NORTH AMERICA INC
6227834,3046,Ciroc Peach Vodka,1,0.0,0.0,3960,DIAGEO NORTH AMERICA INC

In [123]:
zero_price_brands = sales.loc[
    sales["SalesPrice"] == 0, "Brand"
].unique()

purchase_prices[
    purchase_prices["Brand"].isin(zero_price_brands)
][
    ["Brand", "Description", "Price", "Size",
     "PurchasePrice", "VendorNumber", "VendorName"]
].drop_duplicates().head(30)

,Brand,Description,Price,Size,PurchasePrice,VendorNumber,VendorName
553,3046,Ciroc Peach Vodka,47.99,1750mL,35.81,3960,DIAGEO NORTH AMERICA INC
4481,19669,Murphy-Goode Homefront Red,11.99,750mL,6.06,9552,M S WALKER INC
7554,3963,Menage A Trois Vodka,14.99,750mL,11.36,8892,TRINCHERO FAMILY ESTATES
9312,25340,Dom La Soumade Rast Prestige,24.99,750mL,17.23,4425,MARTIGNETTI COMPANIES
9973,19465,Flagstone Longitude Red,6.99,750mL,4.72,2000,SOUTHERN WINE & SPIRITS NE

In [124]:
sales["CalculatedSales"] = (
    sales["SalesQuantity"] * sales["SalesPrice"]
)

sales[["SalesQuantity", "SalesPrice", "SalesDollars", "CalculatedSales"]].head(10)

   SalesQuantity  SalesPrice  SalesDollars  CalculatedSales
0              1       16.49         16.49            16.49
1              2       16.49         32.98            32.98
2              1       16.49         16.49            16.49
3              1       14.49         14.49            14.49
4              2       34.99         69.98            69.98
5              1       34.99         34.99            34.99
6              1       34.99         34.99            34.99
7              1       34.99         34.99            34.99
8              4       14.99         59.96            59.96
9              1       14.99         14.99            14.99

In [125]:
sales["SalesDifference"] = (
    sales["SalesDollars"] - sales["CalculatedSales"]
)

sales["SalesDifference"].describe()

count    1.282536e+07
mean     2.949375e-16
std      7.796303e-15
min     -3.637979e-12
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      3.637979e-12
Name: SalesDifference, dtype: float64

In [126]:
(sales["SalesDifference"].abs() > 0.01).sum()

np.int64(0)

In [127]:
sales.drop(
    columns=["CalculatedSales", "SalesDifference"],
    inplace=True
)

In [128]:
sales.shape

(12825363, 15)

In [129]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName', 'VendorID'],
      dtype='str')

In [130]:
sales.drop(columns=["VendorID"], inplace=True)

In [131]:
sales.shape

(12825363, 14)

In [132]:
sales.nlargest(
    10, "SalesQuantity"
)[
    ["Brand", "Description", "SalesQuantity",
     "SalesPrice", "SalesDollars",
     "VendorNo", "VendorName"]
]

,Brand,Description,SalesQuantity,SalesPrice,SalesDollars,VendorNo,VendorName
12650548,8111,Smirnoff 80 Proof,1231,0.99,1218.69,3960,DIAGEO NORTH AMERICA INC
6130215,3851,Grey Goose Vodka,1176,12.99,15276.24,480,BACARDI USA INC
4073375,8475,J Roget Extra Dry,1016,1.79,1818.64,1392,CONSTELLATION BRANDS INC
1269763,8475,J Roget Extra Dry,1010,1.79,1807.90,1392,CONSTELLATION BRANDS INC
9980640,4277,Bacardi Limon Rum,841,4.49,3776.09,480,BACARDI USA INC
6146927,3858,Grey Goose Vodka,807,22.99,18552.93,480,BACARDI USA INC
6132415,4404,Bacardi Gold Rum,721,5.49,3958.29,480,BACARDI USA INC
6993434,4246,Bacardi Superior Rum,721,5.49,3958.29,480,BACARDI USA INC
6131822,4246,Bacardi Superior Rum,720,5.49,3952.80,480,BACARDI USA INC
10677039,5404,E & J Superior Rsv VSOP,720,5.49,3952.80,3252,E & J GALLO WINERY

In [133]:
Q1 = sales["SalesQuantity"].quantile(0.25)
Q3 = sales["SalesQuantity"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

Q1: 1.0
Q3: 2.0
IQR: 1.0
Lower Bound: -0.5
Upper Bound: 3.5

In [134]:
outlier_count = (
    sales["SalesQuantity"] > upper_bound
).sum()

print("Quantity outliers:", outlier_count)
print(
    "Percentage:",
    round(outlier_count / len(sales) * 100, 2),
    "%"
)

Quantity outliers: 2103063
Percentage: 16.4 %

In [135]:
sales["SalesQuantity"].skew()

np.float64(26.248187953347422)

In [136]:
sales["SalesDollars"].skew()

np.float64(40.92469128174545)

In [137]:
print("Negative Quantity:", (sales["SalesQuantity"] < 0).sum())
print("Negative SalesDollars:", (sales["SalesDollars"] < 0).sum())
print("Negative SalesPrice:", (sales["SalesPrice"] < 0).sum())
print("Negative Volume:", (sales["Volume"] < 0).sum())
print("Negative ExciseTax:", (sales["ExciseTax"] < 0).sum())

Negative Quantity: 0
Negative SalesDollars: 0
Negative SalesPrice: 0
Negative Volume: 0
Negative ExciseTax: 0

In [138]:
purchases[
    ["PurchasePrice", "Quantity", "Dollars"]
].describe()

       PurchasePrice      Quantity       Dollars
count   2.372474e+06  2.372474e+06  2.372474e+06
mean    1.205005e+01  1.415585e+01  1.356815e+02
std     1.794510e+01  2.344616e+01  2.816649e+02
min     0.000000e+00  1.000000e+00  0.000000e+00
25%     6.120000e+00  6.000000e+00  4.926000e+01
50%     9.220000e+00  1.000000e+01  8.393000e+01
75%     1.449000e+01  1.200000e+01  1.405200e+02
max     5.681810e+03  3.816000e+03  5.017570e+04

In [139]:
print("Zero PurchasePrice:", (purchases["PurchasePrice"] == 0).sum())
print("Zero Dollars:", (purchases["Dollars"] == 0).sum())

Zero PurchasePrice: 153
Zero Dollars: 153

In [140]:
purchases[
    (purchases["PurchasePrice"] == 0) |
    (purchases["Dollars"] == 0)
][
    ["VendorNumber", "VendorName", "Brand", "Description",
     "PurchasePrice", "Quantity", "Dollars"]
].head(20)

,VendorNumber,VendorName,Brand,Description,PurchasePrice,Quantity,Dollars
1369009,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0
1369018,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0
1369031,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0
1369032,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0
1369033,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0
1369043,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0
1369045,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0
1369058,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0
1369060,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0
1369063,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0
1369069,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0
1369078,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0
1369089,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0
1369092,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0
1369097,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0
1369104,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0
1369106,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0
1369125,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0
1369132,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0
1369136,2561,EDRINGTON AMERICAS,2166,The Macallan Double Cask 12,0.0,12,0.0

In [141]:
purchases[
    (purchases["PurchasePrice"] == 0) |
    (purchases["Dollars"] == 0)
][["PurchasePrice", "Quantity", "Dollars"]].value_counts()

PurchasePrice  Quantity  Dollars
0.0            12        0.0        110
               11        0.0         23
               24        0.0          4
               10        0.0          4
               5         0.0          3
               9         0.0          2
               48        0.0          2
               36        0.0          2
               71        0.0          1
               33        0.0          1
               1         0.0          1
Name: count, dtype: int64

In [142]:
purchases = purchases[
    purchases["PurchasePrice"] > 0
].copy()

In [143]:
print(purchases.shape)
print("Zero PurchasePrice:", (purchases["PurchasePrice"] == 0).sum())
print("Zero Dollars:", (purchases["Dollars"] == 0).sum())

(2372321, 16)
Zero PurchasePrice: 0
Zero Dollars: 0

In [144]:
purchases["CalculatedDollars"] = (
    purchases["Quantity"] * purchases["PurchasePrice"]
)

purchases["PurchaseDifference"] = (
    purchases["Dollars"] - purchases["CalculatedDollars"]
)

purchases["PurchaseDifference"].describe()

count    2.372321e+06
mean     4.621123e-17
std      2.510270e-14
min     -3.637979e-12
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      3.637979e-12
Name: PurchaseDifference, dtype: float64

In [145]:
(purchases["PurchaseDifference"].abs() > 0.01).sum()

np.int64(0)

In [146]:
purchases.drop(
    columns=["CalculatedDollars", "PurchaseDifference"],
    inplace=True
)

In [147]:
purchases.shape

(2372321, 16)

In [148]:
purchases.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'VendorNumber',
       'VendorName', 'PONumber', 'PODate', 'ReceivingDate', 'InvoiceDate',
       'PayDate', 'PurchasePrice', 'Quantity', 'Dollars', 'Classification'],
      dtype='str')

In [149]:
purchases[
    ["PODate", "ReceivingDate", "InvoiceDate", "PayDate"]
].dtypes

PODate           datetime64[us]
ReceivingDate    datetime64[us]
InvoiceDate      datetime64[us]
PayDate          datetime64[us]
dtype: object

In [150]:
print(
    "Receiving before PO:",
    (purchases["ReceivingDate"] < purchases["PODate"]).sum()
)

print(
    "Invoice before Receiving:",
    (purchases["InvoiceDate"] < purchases["ReceivingDate"]).sum()
)

print(
    "Payment before Invoice:",
    (purchases["PayDate"] < purchases["InvoiceDate"]).sum()
)

Receiving before PO: 0
Invoice before Receiving: 0
Payment before Invoice: 0

In [151]:
purchases["ReceivingDays"] = (
    purchases["ReceivingDate"] - purchases["PODate"]
).dt.days

purchases["InvoiceDays"] = (
    purchases["InvoiceDate"] - purchases["ReceivingDate"]
).dt.days

purchases["PaymentDays"] = (
    purchases["PayDate"] - purchases["InvoiceDate"]
).dt.days

In [152]:
purchases[
    ["ReceivingDays", "InvoiceDays", "PaymentDays"]
].describe()

       ReceivingDays   InvoiceDays   PaymentDays
count   2.372321e+06  2.372321e+06  2.372321e+06
mean    7.620735e+00  8.872530e+00  3.565882e+01
std     2.208865e+00  2.975599e+00  6.062985e+00
min     3.000000e+00  1.000000e+00  2.300000e+01
25%     6.000000e+00  7.000000e+00  3.100000e+01
50%     8.000000e+00  9.000000e+00  3.600000e+01
75%     9.000000e+00  1.100000e+01  4.100000e+01
max     1.400000e+01  1.500000e+01  4.800000e+01

In [153]:
purchases.isnull().sum()

InventoryId       0
Store             0
Brand             0
Description       0
Size              0
VendorNumber      0
VendorName        0
PONumber          0
PODate            0
ReceivingDate     0
InvoiceDate       0
PayDate           0
PurchasePrice     0
Quantity          0
Dollars           0
Classification    0
ReceivingDays     0
InvoiceDays       0
PaymentDays       0
dtype: int64

In [154]:
purchase_prices[
    ["Price", "Volume", "PurchasePrice"]
].describe()

              Price  PurchasePrice
count  12261.000000   12261.000000
mean      38.640240      26.488220
std      206.151172     156.182948
min        0.000000       0.000000
25%       10.990000       6.890000
50%       15.990000      10.650000
75%       29.990000      20.130000
max    13999.900000   11111.030000

In [155]:
print(
    "Zero Price:",
    (purchase_prices["Price"] == 0).sum()
)

print(
    "Zero PurchasePrice:",
    (purchase_prices["PurchasePrice"] == 0).sum()
)

Zero Price: 2
Zero PurchasePrice: 1

In [156]:
purchase_prices[
    (purchase_prices["Price"] == 0) |
    (purchase_prices["PurchasePrice"] == 0)
][
    ["Brand", "Description", "Price", "Size",
     "Volume", "PurchasePrice",
     "VendorNumber", "VendorName"]
]

,Brand,Description,Price,Size,Volume,PurchasePrice,VendorNumber,VendorName
7915,4202,NaN,0.0,NaN,NaN,11.19,480,BACARDI USA INC
10803,2166,The Macallan Double Cask 12,0.0,750mL,750,0.00,2561,EDRINGTON AMERICAS

In [157]:
purchase_prices = purchase_prices[
    (purchase_prices["Price"] > 0) &
    (purchase_prices["PurchasePrice"] > 0)
].copy()

In [158]:
print(purchase_prices.shape)
print("Zero Price:", (purchase_prices["Price"] == 0).sum())
print("Zero PurchasePrice:", (purchase_prices["PurchasePrice"] == 0).sum())

(12259, 9)
Zero Price: 0
Zero PurchasePrice: 0

In [159]:
purchase_prices.isnull().sum()

Brand             0
Description       0
Price             0
Size              0
Volume            0
Classification    0
PurchasePrice     0
VendorNumber      0
VendorName        0
dtype: int64

In [160]:
purchase_prices.duplicated().sum()

np.int64(0)

In [161]:
purchase_prices.duplicated(
    subset=["Brand", "VendorNumber"]
).sum()

np.int64(0)

In [162]:
purchase_prices.dtypes

Brand               int64
Description           str
Price             float64
Size                  str
Volume                str
Classification      int64
PurchasePrice     float64
VendorNumber        int64
VendorName            str
dtype: object

In [163]:
print("Sales start:", sales["SalesDate"].min())
print("Sales end:", sales["SalesDate"].max())

Sales start: 2024-01-01 00:00:00
Sales end: 2024-12-31 00:00:00

In [164]:
print("Purchase start:", purchases["PODate"].min())
print("Purchase end:", purchases["PODate"].max())

Purchase start: 2023-12-20 00:00:00
Purchase end: 2024-12-23 00:00:00

In [165]:
sales[["Brand", "VendorNo", "VendorName"]].drop_duplicates().shape

(11272, 3)

In [166]:
sales[["Brand", "VendorNo"]].drop_duplicates().shape

(11272, 2)

In [167]:
brand_vendor_counts = (
    sales.groupby("Brand")["VendorNo"]
    .nunique()
    .sort_values(ascending=False)
)

brand_vendor_counts.head(10)

Brand
5296     2
5297     2
5298     2
2717     2
5299     2
18254    2
2158     2
5270     2
5273     2
809      2
Name: VendorNo, dtype: int64

In [168]:
vendor_brand_counts = (
    sales.groupby("VendorNo")["Brand"]
    .nunique()
    .sort_values(ascending=False)
)

vendor_brand_counts.head(10)

VendorNo
4425     1495
9165      883
9552      882
10754     839
3252      510
1392      461
7153      425
3960      415
12546     389
2000      371
Name: Brand, dtype: int64

In [169]:
purchases.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'VendorNumber',
       'VendorName', 'PONumber', 'PODate', 'ReceivingDate', 'InvoiceDate',
       'PayDate', 'PurchasePrice', 'Quantity', 'Dollars', 'Classification',
       'ReceivingDays', 'InvoiceDays', 'PaymentDays'],
      dtype='str')

In [170]:
purchases[["Brand", "VendorNumber"]].drop_duplicates().shape

(10692, 2)

In [171]:
sales_keys = set(
    zip(sales["Brand"], sales["VendorNo"])
)

price_keys = set(
    zip(purchase_prices["Brand"], purchase_prices["VendorNumber"])
)

print("Sales keys:", len(sales_keys))
print("Purchase price keys:", len(price_keys))

print("Matching keys:", len(sales_keys & price_keys))

print(
    "Sales keys without purchase price:",
    len(sales_keys - price_keys)
)

Sales keys: 11272
Purchase price keys: 12259
Matching keys: 11224
Sales keys without purchase price: 48

In [172]:
print(
    "Match rate:",
    round(len(sales_keys & price_keys) / len(sales_keys) * 100, 2),
    "%"
)

Match rate: 99.57 %

In [173]:
unmatched_sales_keys = sales[
    ~sales.set_index(["Brand", "VendorNo"]).index.isin(
        purchase_prices.set_index(["Brand", "VendorNumber"]).index
    )
]

unmatched_sales_keys[
    ["Brand", "Description", "VendorNo", "VendorName"]
].drop_duplicates().sort_values("Brand")

,Brand,Description,VendorNo,VendorName
5835154,809,Southern Comfort,8004,SAZERAC CO INC
7155918,1236,Southern Comfort & Egg Nog,8004,SAZERAC CO INC
5840166,2158,Sortilege Liqueur,6830,PARK STREET IMPORTS LLC
7063288,2166,The Macallan Double Cask 12,2561,EDRINGTON AMERICAS
5913253,2232,Sipsmith Gin,9165,ULTRA BEVERAGE COMPANY LLP
7419321,2495,Virginia Highland Malt Whsky,9165,ULTRA BEVERAGE COMPANY LLP
6031969,2717,Big Peat Scotch,7153,PINE STATE TRADING CO
5823649,2879,Corner Creek Rsv Bourbon,9165,ULTRA BEVERAGE COMPANY LLP
6392071,4256,English Harbour Rum,9165,ULTRA BEVERAGE COMPANY LLP
5902556,4884,Bayou Silver Rum,8664,"STOLI GROUP,(USA) LLC"
5902576,4904,Bayou Spiced Rum,8664,"STOLI GROUP,(USA) LLC"
5831707,5075,Tuaca Italian Liqueur,8004,SAZERAC CO INC
5832044,5197,Southern Comfort,8004,SAZERAC CO INC
5832205,5270,Southern Comfort,8004,SAZERAC CO INC
6425333,5273,Southern Comfort 100 Proof,8004,SAZERAC CO INC
5832245,5296,Southern Comfort 100 Proof,8004,SAZERAC CO INC
5832248,5297,Southern Comfort,8004,SAZERAC CO INC
5832265,5298,Southern Comfort 100 Proof,8004,SAZERAC CO INC
5832272,5299,Southern Comfort,8004,SAZERAC CO INC
6133798,5322,Linie Aquavit,8004,SAZERAC CO INC
6109247,5434,Southern Comfort Caramel,8004,SAZERAC CO INC
6044757,6346,Amaretto Villa Vittoria Liq,4425,MARTIGNETTI COMPANIES
5834157,6692,Jaboulet Cotes du Rhone Par,10754,PERFECTA WINES
5953910,6942,Southern Comfort Cherry,8004,SAZERAC CO INC
5834910,8015,Bayou Satsuma Rum Liqueur,8664,"STOLI GROUP,(USA) LLC"
7220970,8108,Amaras Cupreata Mezcal,9165,ULTRA BEVERAGE COMPANY LLP
7058741,8238,Suerte Blanco Tequila,9165,ULTRA BEVERAGE COMPANY LLP
7058820,8284,Suerte Reposado Tequila,9165,ULTRA BEVERAGE COMPANY LLP
5907199,8505,Hussong's Repasado Tequila,5992,MCCORMICK DISTILLING CO
5817926,11089,Jaboulet Cts Rhone Parl Rose,10754,PERFECTA WINES
6155409,11259,Jaboulet Crozes Herm 10 Thal,10754,PERFECTA WINES
5820239,17754,Chocolate Shop Red,10754,PERFECTA WINES
6851086,18254,Jaboulet 09 Dom Terre Ferme,10754,PERFECTA WINES
6999649,18771,Cigar Zin Old Vine Zinfandel,9165,ULTRA BEVERAGE COMPANY LLP
6218863,20913,Benton Lane First Class Pnt,9552,M S WALKER INC
7593456,21653,Pendulum Red,10754,PERFECTA WINES
6162785,21860,Le Grande Courtage Brut,9552,M S WALKER INC
6001237,21959,Le Grande Courtage Brut,9552,M S WALKER INC
6894698,21960,Le Grande Courtage Rose,9552,M S WALKER INC
5840556,23472,Dom Vocoret & Fils Chabls 13,4425,MARTIGNETTI COMPANIES
6163660,23473,Auvigue Saint-Veran 13,4425,MARTIGNETTI COMPANIES
6669041,26889,Jaboulet Crozes Hermitage L,10754,PERFECTA WINES
5861432,31384,Benton Lane Pnt Nr Ore,9552,M S WALKER INC
6172764,35977,Jaboulet Cotes du Rhone Par,10754,PERFECTA WINES
5848576,42735,Magnificent Wine Co House Re,10754,PERFECTA WINES
5865954,42801,Benton Lane Pnt Gris Willamt,9552,M S WALKER INC
6682988,43937,P Jaboulet Hrmtg 10 Chapelle,10754,PERFECTA WINES
6190381,90609,Flavor Essence Variety 5 Pak,201359,FLAVOR ESSENCE INC

In [174]:
unmatched_sales_keys[
    ["Brand", "Description", "VendorNo", "VendorName"]
].drop_duplicates().shape

(48, 4)

In [175]:
unmatched_sales = sales[
    ~sales.set_index(["Brand", "VendorNo"]).index.isin(
        purchase_prices.set_index(["Brand", "VendorNumber"]).index
    )
]

print("Unmatched sales rows:", len(unmatched_sales))
print(
    "Percentage of sales rows:",
    round(len(unmatched_sales) / len(sales) * 100, 4),
    "%"
)

Unmatched sales rows: 40995
Percentage of sales rows: 0.3196 %

In [176]:
sales["VendorNumber"] = sales["VendorNo"]

In [177]:
sales = sales.drop(columns=["VendorNo"])

In [178]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorName', 'VendorNumber'],
      dtype='str')

In [179]:
sales_summary = (
    sales.groupby(["Brand", "VendorNumber"])
    .agg(
        TotalSalesQuantity=("SalesQuantity", "sum"),
        TotalSalesDollars=("SalesDollars", "sum"),
        TotalExciseTax=("ExciseTax", "sum")
    )
    .reset_index()
)

In [180]:
sales_summary.shape

(11272, 5)

In [181]:
sales_summary.head()

   Brand  VendorNumber  TotalSalesQuantity  TotalSalesDollars  TotalExciseTax
0     58          8320                3446           43341.54         2715.12
1     60         12546                1775           18716.25         1398.56
2     61          8004                 312            4364.88          245.70
3     62          1128                3125          119863.75         2463.18
4     63          1128                2778          112249.22         2190.45

In [182]:
purchase_summary = (
    purchases.groupby(["Brand", "VendorNumber"])
    .agg(
        TotalPurchaseQuantity=("Quantity", "sum"),
        TotalPurchaseDollars=("Dollars", "sum"),
        AvgPurchasePrice=("PurchasePrice", "mean")
    )
    .reset_index()
)

In [183]:
purchase_summary.shape

(10692, 5)

In [184]:
purchase_summary.head()

,Brand,VendorNumber,TotalPurchaseQuantity,TotalPurchaseDollars,AvgPurchasePrice
0,58,8320,3550,32944.0,9.28
1,60,12546,1633,12084.2,7.40
2,61,8004,312,3307.2,10.60
3,62,1128,3200,91744.0,28.67
4,63,1128,2855,86963.3,30.46

In [185]:
vendor_performance = sales_summary.merge(
    purchase_summary,
    on=["Brand", "VendorNumber"],
    how="left"
)

In [186]:
vendor_performance.shape

(11272, 8)

In [187]:
vendor_performance.isna().sum()

Brand                      0
VendorNumber               0
TotalSalesQuantity         0
TotalSalesDollars          0
TotalExciseTax             0
TotalPurchaseQuantity    758
TotalPurchaseDollars     758
AvgPurchasePrice         758
dtype: int64

In [188]:
print("Sales combinations:", len(sales_summary))
print("Purchase combinations:", len(purchase_summary))

print(
    "Sales combinations without purchases:",
    len(
        sales_summary.merge(
            purchase_summary,
            on=["Brand", "VendorNumber"],
            how="left",
            indicator=True
        ).query("_merge == 'left_only'")
    )
)

Sales combinations: 11272
Purchase combinations: 10692
Sales combinations without purchases: 758

In [189]:
print(
    vendor_performance[
        vendor_performance["TotalPurchaseQuantity"].isna()
    ][["Brand", "VendorNumber"]].drop_duplicates().shape
)

(758, 2)

In [190]:
vendor_names = (
    sales[["VendorNumber", "VendorName"]]
    .drop_duplicates()
)

In [191]:
vendor_names["VendorNumber"].duplicated().sum()

np.int64(3)

In [192]:
vendor_names[
    vendor_names["VendorNumber"].duplicated(keep=False)
].sort_values("VendorNumber")

          VendorNumber                   VendorName
1009              1587  VINEYARD BRANDS INC
10748135          1587  VINEYARD BRANDS LLC
8225794           2000  SOUTHERN GLAZERS W&S OF NE
8                 2000  SOUTHERN WINE & SPIRITS NE
2555              4425       MARTIGNETTI COMPANIES
40                4425        MARTIGNETTI COMPANIES

In [193]:
vendor_names = (
    sales.groupby("VendorNumber")["VendorName"]
    .agg(lambda x: x.mode()[0])
    .reset_index()
)

In [194]:
vendor_names["VendorNumber"].duplicated().sum()

np.int64(0)

In [195]:
vendor_names[
    vendor_names["VendorNumber"].isin([1587, 2000, 4425])
]

    VendorNumber                   VendorName
19          1587  VINEYARD BRANDS INC
25          2000  SOUTHERN WINE & SPIRITS NE
42          4425        MARTIGNETTI COMPANIES

In [196]:
vendor_performance = vendor_performance.merge(
    vendor_names,
    on="VendorNumber",
    how="left"
)

In [197]:
vendor_performance.shape

(11272, 9)

In [198]:
vendor_performance["GrossProfit"] = (
    vendor_performance["TotalSalesDollars"]
    - vendor_performance["TotalPurchaseDollars"]
)

In [199]:
vendor_performance["ProfitMargin"] = (
    vendor_performance["GrossProfit"]
    / vendor_performance["TotalSalesDollars"]
    * 100
)

In [200]:
vendor_performance["SalesToPurchaseRatio"] = (
    vendor_performance["TotalSalesDollars"]
    / vendor_performance["TotalPurchaseDollars"]
)

In [201]:
vendor_performance[
    [
        "VendorNumber",
        "VendorName",
        "TotalSalesDollars",
        "TotalPurchaseDollars",
        "GrossProfit",
        "ProfitMargin",
        "SalesToPurchaseRatio"
    ]
].head(10)

,VendorNumber,VendorName,TotalSalesDollars,TotalPurchaseDollars,GrossProfit,ProfitMargin,SalesToPurchaseRatio
0,8320,SHAW ROSS INT L IMP LTD,43341.54,32944.00,10397.54,23.989780,1.315613
1,12546,JIM BEAM BRANDS COMPANY,18716.25,12084.20,6632.05,35.434716,1.548820
2,8004,SAZERAC CO INC,4364.88,3307.20,1057.68,24.231594,1.319811
3,1128,BROWN-FORMAN CORP,119863.75,91744.00,28119.75,23.459762,1.306502
4,1128,BROWN-FORMAN CORP,112249.22,86963.30,25285.92,22.526589,1.290765
5,9165,ULTRA BEVERAGE COMPANY LLP,349.86,195.44,154.42,44.137655,1.790115
6,9165,ULTRA BEVERAGE COMPANY LLP,17325.31,11932.27,5393.04,31.128101,1.451971
7,7245,PROXIMO SPIRITS INC.,314.79,109.40,205.39,65.246672,2.877422
8,7245,PROXIMO SPIRITS INC.,143416.71,113583.48,29833.23,20.801781,1.262655
9,7245,PROXIMO SPIRITS INC.,78923.14,55593.98,23329.16,29.559341,1.419635

In [202]:
vendor_performance["GrossProfit"] = vendor_performance["GrossProfit"].round(2)

vendor_performance["ProfitMargin"] = vendor_performance["ProfitMargin"].round(2)

vendor_performance["SalesToPurchaseRatio"] = (
    vendor_performance["SalesToPurchaseRatio"].round(2)
)

In [203]:
vendor_performance.head()

,Brand,VendorNumber,TotalSalesQuantity,TotalSalesDollars,TotalExciseTax,TotalPurchaseQuantity,TotalPurchaseDollars,AvgPurchasePrice,VendorName,GrossProfit,ProfitMargin,SalesToPurchaseRatio
0,58,8320,3446,43341.54,2715.12,3550.0,32944.0,9.28,SHAW ROSS INT L IMP LTD,10397.54,23.99,1.32
1,60,12546,1775,18716.25,1398.56,1633.0,12084.2,7.40,JIM BEAM BRANDS COMPANY,6632.05,35.43,1.55
2,61,8004,312,4364.88,245.70,312.0,3307.2,10.60,SAZERAC CO INC,1057.68,24.23,1.32
3,62,1128,3125,119863.75,2463.18,3200.0,91744.0,28.67,BROWN-FORMAN CORP,28119.75,23.46,1.31
4,63,1128,2778,112249.22,2190.45,2855.0,86963.3,30.46,BROWN-FORMAN CORP,25285.92,22.53,1.29

In [204]:
[name for name in dir() if not name.startswith("_")]

['IQR',
 'In',
 'Out',
 'Q1',
 'Q3',
 'begin_inventory',
 'brand_vendor_counts',
 'col',
 'date_columns',
 'end_inventory',
 'exit',
 'get_ipython',
 'lower_bound',
 'missing_city',
 'open',
 'os',
 'outlier_count',
 'pd',
 'price_keys',
 'purchase_prices',
 'purchase_summary',
 'purchase_vendors',
 'purchases',
 'quit',
 'sales',
 'sales_keys',
 'sales_summary',
 'sales_vendors',
 'unmatched_sales',
 'unmatched_sales_keys',
 'upper_bound',
 'vendor_brand_counts',
 'vendor_invoice',
 'vendor_mapping',
 'vendor_name_counts',
 'vendor_names',
 'vendor_number_counts',
 'vendor_performance',
 'vendor_sales_summary',
 'zero_price_brands']

In [205]:
print("Beginning inventory:")
print(begin_inventory.shape)
print(begin_inventory.columns)

print("\nEnding inventory:")
print(end_inventory.shape)
print(end_inventory.columns)

Beginning inventory:
(206529, 9)
Index(['InventoryId', 'Store', 'City', 'Brand', 'Description', 'Size',
       'onHand', 'Price', 'startDate'],
      dtype='str')

Ending inventory:
(224489, 9)
Index(['InventoryId', 'Store', 'City', 'Brand', 'Description', 'Size',
       'onHand', 'Price', 'endDate'],
      dtype='str')

In [206]:
begin_inventory_summary = (
    begin_inventory
    .groupby("Brand", as_index=False)["onHand"]
    .sum()
    .rename(columns={"onHand": "BeginningInventory"})
)

In [207]:
end_inventory_summary = (
    end_inventory
    .groupby("Brand", as_index=False)["onHand"]
    .sum()
    .rename(columns={"onHand": "EndingInventory"})
)

In [208]:
inventory_summary = begin_inventory_summary.merge(
    end_inventory_summary,
    on="Brand",
    how="outer"
)

In [209]:
print(inventory_summary.shape)
print(inventory_summary.isna().sum())
print(inventory_summary.head())

(10759, 3)
Brand                    0
BeginningInventory    2665
EndingInventory       1106
dtype: int64
   Brand  BeginningInventory  EndingInventory
0     58               281.0            385.0
1     60               288.0            146.0
2     61                12.0             12.0
3     62               384.0            459.0
4     63               365.0            442.0

In [210]:
vendor_inventory_check = vendor_performance.merge(
    inventory_summary,
    on="Brand",
    how="left"
)

print(vendor_inventory_check.shape)

print(
    "Missing Beginning Inventory:",
    vendor_inventory_check["BeginningInventory"].isna().sum()
)

print(
    "Missing Ending Inventory:",
    vendor_inventory_check["EndingInventory"].isna().sum()
)

(11272, 14)
Missing Beginning Inventory: 3216
Missing Ending Inventory: 1837

In [211]:
vendor_inventory_check[
    ["Brand", "VendorNumber", "BeginningInventory", "EndingInventory"]
].head(10)

   Brand  VendorNumber  BeginningInventory  EndingInventory
0     58          8320               281.0            385.0
1     60         12546               288.0            146.0
2     61          8004                12.0             12.0
3     62          1128               384.0            459.0
4     63          1128               365.0            442.0
5     70          9165                 NaN              NaN
6     72          9165               151.0            139.0
7     75          7245                18.0              7.0
8     77          7245              1261.0           1764.0
9     79          7245               902.0            995.0

In [212]:
vendor_inventory_check["AverageInventory"] = (
    vendor_inventory_check["BeginningInventory"]
    + vendor_inventory_check["EndingInventory"]
) / 2

vendor_inventory_check["StockTurnover"] = (
    vendor_inventory_check["TotalSalesQuantity"]
    / vendor_inventory_check["AverageInventory"]
)

In [213]:
vendor_inventory_check[
    [
        "VendorNumber",
        "VendorName",
        "TotalSalesQuantity",
        "BeginningInventory",
        "EndingInventory",
        "AverageInventory",
        "StockTurnover"
    ]
].head(10)

,VendorNumber,VendorName,TotalSalesQuantity,BeginningInventory,EndingInventory,AverageInventory,StockTurnover
0,8320,SHAW ROSS INT L IMP LTD,3446,281.0,385.0,333.0,10.348348
1,12546,JIM BEAM BRANDS COMPANY,1775,288.0,146.0,217.0,8.179724
2,8004,SAZERAC CO INC,312,12.0,12.0,12.0,26.000000
3,1128,BROWN-FORMAN CORP,3125,384.0,459.0,421.5,7.413998
4,1128,BROWN-FORMAN CORP,2778,365.0,442.0,403.5,6.884758
5,9165,ULTRA BEVERAGE COMPANY LLP,14,NaN,NaN,NaN,NaN
6,9165,ULTRA BEVERAGE COMPANY LLP,469,151.0,139.0,145.0,3.234483
7,7245,PROXIMO SPIRITS INC.,21,18.0,7.0,12.5,1.680000
8,7245,PROXIMO SPIRITS INC.,10429,1261.0,1764.0,1512.5,6.895207
9,7245,PROXIMO SPIRITS INC.,5686,902.0,995.0,948.5,5.994729

In [214]:
import os

print(os.getcwd())

g:\vendor performance analysis\Notebook

In [215]:
"""
sales.to_csv(
    r"G:\vendor performance analysis\Notebook\sales_clean.csv",
    index=False
)
"""

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 51-52: malformed \N character escape (417745599.py, line 1)

In [ ]:
"""
purchase_prices.to_csv(
    r"G:\vendor performance analysis\Notebook\purchase_prices_clean.csv",
    index=False
)

purchases.to_csv(
    r"G:\vendor performance analysis\Notebook\purchases_clean.csv",
    index=False
)

begin_inventory.to_csv(
    r"G:\vendor performance analysis\Notebook\begin_inventory_clean.csv",
    index=False
)

end_inventory.to_csv(
    r"G:\vendor performance analysis\Notebook\end_inventory_clean.csv",
    index=False
)
"""

In [ ]:
print(end_inventory.shape)

(224489, 9)

In [ ]:
"""
end_inventory.to_csv(
    r"G:\vendor performance analysis\Notebook\end_inventory_clean.csv",
    index=False
)
"""

In [216]:
print(purchases.shape)
print(purchases.columns.tolist())

(2372321, 19)
['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'VendorNumber', 'VendorName', 'PONumber', 'PODate', 'ReceivingDate', 'InvoiceDate', 'PayDate', 'PurchasePrice', 'Quantity', 'Dollars', 'Classification', 'ReceivingDays', 'InvoiceDays', 'PaymentDays']